### ISSUE TITLE
update stackage

### ISSUE THREAD

**Issue by agreif** [tdammers/ginger#12]
Hi,
could you please update stackage? There is still the ginger-0.5.3.0 version.
Thanks, ALex.

**Comment by tdammers** [comment]
I'm afraid that's not how stackage works; as a package author / maintainer, I can merely add the package to stackage without any version attached to it (which I have done), upload new versions to hackage (which I have also done), and then stackage will automatically pick up the new version and try to add it to the nightly builds, from where it will eventually pass on into stackage LTS. As you can see [here](https://www.stackage.org/package/ginger), Ginger is currently at 0.7.3.0 in Stackage Nightly, but the last time an LTS release has been assembled (LTS-9.13), Ginger was still at 0.5.3.0, so that's what you get when you use that LTS release for your project.

If you're interested in the details of how stackage maintainership works, check [this](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md) out.

If you want to use 0.7.3.0 in your project, you can do one of the following:

1. Build your project against Stackage Nightly
2. Use `extra-deps` to override the Ginger version in stack.yaml (this will cause `stack` to pull the exact version you specify directly from hackage)
3. Wait for a new LTS release and then use that

**Comment by agreif** [comment]
yesterday they released 9.13, but you made the changes already 11 days ago. So they seem to be quite outdated, or they very seldom pick up the new versions. Never mind, I am currently working with a nightly and will wait for 9.14. Thanks

**Comment by agreif** [comment]
stange, the current 9.14 also does not contain the latest ginger
