### ISSUE TITLE
injection seems to be http escaped

### ISSUE THREAD

**Issue by andrewufrank** [tdammers/ginger#39]
I inject content 
`"content": "<p>What should go into a homepage</p>\n<ul>\n<li>name and address</li>\n</ul>",` 
into {{ content }} and get 
````
  &lt;p&gt;What should go into a homepage&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;name and address&lt;/li&gt;
&lt;/ul&gt;
````
for mustache syntax I would use {{{ context }}} to avoid the http-escaping, but I thought this would not be required for jinja2. What is it I am doing wrong? 
Thank you for help!

**Comment by tdammers** [comment]
This is by design - you are passing in a string, not HTML, so in order to
transform that string into HTML, encoding is necessary. This is exactly how
Ginger leverages Haskell's type system to avoid accidental XSS
vulnerabilities.

If you want to pass in actual HTML, the proper way would be to use the HTML
type, which you can gain from a raw string by wrapping it in the HTML
constructor.

A less nice alternative, if passing the value as a string (or Text) is
inevitable, is to use the `raw` filter inside the template. (The latter is
consistent with Jinja in auto-escaping mode).

A third, absolutely horrible, solution would be to make Ginger output plain
text rather than HTML; in this scenario, it behaves like Jinja with
auto-escaping disabled, i.e., it will never perform automatic HTML-encoding
for you.

In general however, I would strongly suggest avoiding the whole situation
entirely, and never passing pre-encoded HTML (at least not when your code
handles any kind of untrusted data anywhere) - Ginger's type-level HTML
encoding checks are great and all, but they are not fool proof.

On Dec 31, 2018 19:47, "andrew u frank" <notifications@github.com> wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tdammers/ginger/issues/39>, or mute the thread
