### ISSUE TITLE
Custom filter

### ISSUE THREAD

**Issue by MarekSuchanek** [tdammers/ginger#43]
Hello, is it possible to pass own function through the context to be used as function/filter?

I tried after going though the files below but couldn't get it working... Some note on that in docs would be helpful.

https://github.com/tdammers/ginger/blob/f3732ef0b6df2a8c8c6288fff989754e5a34a9fc/src/Text/Ginger/Run.hs#L128-L135

https://github.com/tdammers/ginger/blob/f3732ef0b6df2a8c8c6288fff989754e5a34a9fc/src/Text/Ginger/Run/Builtins.hs#L95-L97

Thanks,
Marek

**Comment by tdammers** [comment]
It is of course possible; however, because Ginger replicates procedure call semantics from Jinja2 (which in turn took it from Python), and because Ginger is unityped, we have to do a bit of marshalling between Ginger and Haskell.

Essentially, a Ginger function is of type `[(Maybe Text, GVal m)] -> m (GVal m)`, where `m` is the "carrier" monad (usually `Run` over some output type `h` and a base monad `m`). The first argument is a list of arguments, in the same order as they are passed in by the caller; the first element of each pair is an optional argument name (`Just` if given, `Nothing` for positional arguments), the second element is the argument value. The function, then, is supposed to return a `GVal` into the carrier monad. For the built-in functions, the overwhelming majority only depends on the features provided by `Run`, so we get a type like `[(Maybe Text, GVal Run m h)] -> Run m h (GVal (Run m h))`.

The trickiest part about writing Ginger functions is untangling the arguments into something you can use; the `extractArgs` family of functions (in `Text.Ginger.Run.FuncUtils`) is supposed to help with that. There are several flavors, depending on whether you want `GVal`s or properly typed arguments, whether you have sensible default values, whether you want your function to be variadic, etc. For common types of functions, there are also the `...Func` wrapper functions, e.g. `binaryFunc`, which takes a regular (pure) binary function over `GVal`s and turns it into a Ginger function, or `variadicNumericFunc`, which takes a function from lists of numbers to number and turns it into a variadic Ginger function.

To pass your Ginger function from the host into a template, you then need to convert it into a `GVal`, which you can do using `fromFunction`; you can then add this `GVal` to the template context like any other.

Filters, then, are really just syntax sugar over functions in Ginger, so a function defined like this is automatically available as a filter, too. When used as a filter, the LHS of the filter expression is passed as the first positional argument, and all the other arguments (if any) are shifted one position to the right. That is: `{{ foo|bar(baz, quux) }}` desugars into `{{ bar(foo, baz, quux) }}`.

Most of this can be figured out from available documentation and type signatures, and I'm unsure what a good place for this kind of explanation would be, but if you have any ideas, feel free to tell (or maybe even fire a merge request my way, that would be double awesome).

HTH.

**Comment by MarekSuchanek** [comment]
Thank you very much for the explanation, it was in the end easier than I expected...

Maybe just include passing a function in "A Worked Example" would be the best option.
