### ISSUE TITLE
How to check if all variables were filled in rendered template?

### ISSUE THREAD

**Issue by vaclavsvejcar** [tdammers/ginger#45]
Hello,
given the following simple template

```jinja
Hello, {{name}} {{surname}}!
```
and function for rendering:

```haskell
renderTemplate :: HashMap Text Text -> Template SourcePos -> Text
renderTemplate = easyRender
```

Is there any built-in way how to check that the rendered template has all variables filled in? I.e.  that the given `HashMap` contains keys for both existing variables `name` and `surname` and if not, then return some error, etc?

I tried to search source codes and documentation but didn't find anything that would help me.
Thanks a lot in advance.

**Comment by tdammers** [comment]
No, this is not currently possible; one problem with this is that
jinja/ginger is quite dynamic, so we can't easily do these checks until we
get to evaluating them at runtime. I have some ideas on static checking
such things, but it's absolutely not a trivial problem. For simple variable
lookups, this information could be extracted statically, but this doesn't
easily generalize, especially when variable names are constructed at
runtime, or when complex conditionals are involved - for example, when the
template already performs a null check on a variable, then not providing it
to the template would arguably be OK.

Another issue is that undefined variables are not actually an error in
jinja, and that is by design - all variables are considered optional and
default to "null". Specifically, we explicitly do not want to mandate
setting Null on all the optional variables explicitly; this could lead to a
lot of boilerplate, and would also bleed the "if not given, use this value
as a default" logic, which belongs in the template, into the host
environment.

And finally, consider that the intended use case for ginger is when you
need to provide templates at runtime. If you can compile your templates
into the application instead, I would recommend using e.g. blaze-html
instead; it's faster, DOM-aware, type-safe, and implemented as a Haskell
EDSL, so you don't have to mess with the wannabe Python that is Ginger's
expression language.

Then again, if there is a demand for it,I could probably be talked into
writing a TH / QQ backend for Ginger, which would allow you to compile
Ginger templates into a Haskell binary, and generate suitable context types
for you, and all that. Such a mechanism would obviously lift definedness
requirements and such to the host language (Haskell), providing some degree
of basic type safety.

**Comment by vaclavsvejcar** [comment]
Thanks a lot for exhaustive response. It's true that _Ginger_ seems to be overkill for my needs and I plan to replace it probably with _Mustache_, as I really need to replace some static placeholders, no advanced templating logic. I'd love to use some compile-time templates, however, it's not possible for my use case. Anyway, thanks for developing this library :-)
