### ISSUE TITLE
performance comparison to yesod hamlet

### ISSUE THREAD

**Issue by agreif** [tdammers/ginger#7]
Hi,
is there any performace comparison to yesod hamlet?
AFAIK yesod hamlet is compiled by template haskell, so that the templates do not have to be reparsed on every request.
Would it make sense to use ginger in webapps eg. replacing hamlet by ginger?

thanks,
Alex.

**Comment by tdammers** [comment]
I haven't done any comparisons of this kind, but if I had to take a bet, I would assume that Hamlet kicks Ginger across the room as far as runtime performance is concerned. However, it's an apples-and-oranged comparison, because Hamlet, like most Haskell template engines, compiles down to Haskell AST (and from there to machine code), while Ginger was designed for interpretation at runtime.

You can of course use Ginger for a web app, and I have tentative plans to make a compile-time backend (which would allow you to compile templates into your binaries just like you would with Hamlet), but right now, the main use case is to allow people to provide templates at runtime, without the need to recompile everything. I'm using Ginger in [Sprinkles](https://sprinkles.tobiasdammers.nl/), if you're interested you might want to look into that to understand these design decisions.

All that said, I believe Ginger's performance is still more than adequate; Ginger powers its own website (https://ginger.tobiasdammers.nl/), the Sprinkles website, and a handful of other sites I've built with Sprinkles, and despite running fairly complex templates, I haven't run into any performance issues yet. In fact, the Ginger and Sprinkles sites run on a 32-bit VPS with 128 MB of RAM, and I'm running some personal-use stuff that also uses Ginger on a first-gen Atom machine on my home network.

You would, of course, still put measures in place to avoid constant re-parsing; Sprinkles caches parsed templates, and the Sprinkles and Ginger sites also run behind a caching reverse proxy and set caching headers to enable client-side caching.

**Comment by agreif** [comment]
thanks for the explanation. I will have a look at Sprinkles soon. 
Anyway thanks for the nice ginger project
cheers,
Alex.
